### ISSUE TITLE
ggfy dplyr dependency

### ISSUE THREAD

**Issue by raffertyparker** [DavZim/varsExtra#1]
ggfy will not run unless dplyr is attached as a library beforehand.
Otherwise it doesn't like the n() in ggfy_varest function, error message:
>Error: Evaluation error: could not find function "n".

**Comment by DavZim** [comment]
Thanks for the report! I fixed it in 5a6f89dbd673f6fca5e68cc133f1a8df0ac8c2e4. The error was that I forgot a `dplyr::` in front of the `n()` function calls.

**Comment by raffertyparker** [comment]
Neat. Great package by the way!

**Comment by DavZim** [comment]
Good to hear that you like/use it! If you have ideas on how to extend it, let me know!

**Comment by raffertyparker** [comment]
Ok, will do.

I also noticed that
df %>%
    dplyr::filter(type != "residuals") %>%

in ggfy seemed to drop every second value for some reason. I only noticed
this as a problem when I went to reintroduce the datetime column to the
dataframe so that I could include times on the plot.

I just altered it my end (just using base R) and it's working fine.

**Comment by DavZim** [comment]
Can you include a small reproducible example, then I will look into it!

**Comment by raffertyparker** [comment]
Well, unfortunately using a reproducible dataset I couldn't replicate the
"dropping every second value" issue.  Spent a fair bit of time trying and I
think I need to move on. For the time being at least.

Essentially what was happening is for a two-variable model, one variable in
the vardf dataframe (see script attached) had even t values and the other
had odd.

I have attached the script I was playing with to try to replicate the
problem, there may be something of use in there. Note I had just copied the
relevant code from the ggfy script, pasted it into markdown blocks and
altered it to suit my ends, a lot of it is no longer running as a function.
This is because when I called ggfy() directly, the plot would include
unwanted "sd1", "sd2" and "sd3" values, (see attached, generated from my
dataset not the reproducible one).

Key points:
- ggfy() sometimes outputs a plot with unwanted "variables"
- It would be nice if VAR preserved timestamps*. Currently I need to call
VAR() without the time column and then cut and paste the times back in
afterwards, shifted according to the p value. Having this would provide the
ability to "zoom in" on sections of plot to see how well the model is
replicating the data at particular times of interest, as well as calculate
(say) daily averages.

* When I try to feed my data including the timestamp column into VAR() my
computer hangs. Perhaps this is just an issue with my computer.

Hope this is of some use. Disclaimer, if it wasn't painfully obvious
already I'm relatively new to R (and programming in general). If you see
anything I've done that's particularly bad practice please let me know!

Cheers,

Rafferty.
